image: node:10.1

before_script:
  - apt -y update
  - wget https://www.python.org/ftp/python/3.5.0/Python-3.5.0.tar.xz
  - tar Jxfv Python-3.5.0.tar.xz
  - cd Python-3.5.0
  - ./configure; make; make install
  - alias python3='python3.5'; alias pip3='pip3.5'
  - cd ..
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt

pages:
  script:
    - python3 setup.py bdist_wheel sdist
    - mkdir -p public/bin
    - cp dist/* public/bin
    - ls public/bin

  artifacts:
    paths:
    - public

  only:
    - /^suwa\/.*$/
